name: Omni Comment
description: Combine outputs from many jobs into a single comment
branding:
  icon: message-circle
  color: blue
inputs:
  section:
    description: The section ID that matches with the value in omni-comment.yml
    required: true
  token:
    description: GitHub auth token
    default: ${{ github.token }}
  title:
    description: A title for the section. When this is specified, the section will be rendered as a
      expandable/collapsible section.
  collapsed:
    description: Collapse the section by default. Only used if title is set.
    default: 'false'
  message:
    description: Comment body
  file-path:
    description: File path containing the comment body
  pr-number:
    description: The pull request number where to create the comment
  config:
    description: Path to the config file
    default: .github/omni-comment.yml
runs:
  using: node20
  main: dist/index.js
